### ISSUE TITLE
Setup WSL in Clion.

### ISSUE THREAD

**Issue by a-gafiyatullin** [neko2a/mvds#5]
0. Make sure that WSL and latest CLion are installed on your PC.
2. Setup WSL in Clion like in article: https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-product.html#wsl-tooclhain
3. Delete configuration "Visual Studio".
4. Check if Cmake does not find any build errors. Try to build release/debug shared library(.so). Check if it exists in cmake-build-(release/debug) folder.

**Comment by neko2a** [comment]
Done
